In [1]:
import pandas as pd
#import

url = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

database_cars = pd.read_csv(url)

display(database_cars)

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [2]:
display(database_cars)

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [3]:
mean_df = database_cars['MSRP'].mean()


display(mean_df)

40594.737032063116

In [4]:

database_cars.loc[database_cars['Make']=='BMW','MSRP'].mean()

61546.76347305389

In [5]:


database_cars[database_cars.Make == 'BMW'].MSRP.mean()

61546.76347305389

Question 4: Number of missing values in "Engine HP" after 2015 (including 2015) *

In [6]:
database_cars['Engine HP'].isnull().sum


database_cars[ # returns only true values (after 2015)
   database_cars['Year'] >= 2015 #returns a binary series 
].isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [7]:
database_cars.isnull().sum()


Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [8]:
database_cars[database_cars.Year>= 2015]['Engine HP'].isnull().sum()

51

In [9]:

database_cars[database_cars['Engine HP'].isnull()]

# AVG 249.38



Make        Model  Year                Engine Fuel Type  Engine HP  \
539      FIAT         500e  2015                        electric        NaN   
540      FIAT         500e  2016                        electric        NaN   
541      FIAT         500e  2017                        electric        NaN   
2905  Lincoln  Continental  2017  premium unleaded (recommended)        NaN   
2906  Lincoln  Continental  2017  premium unleaded (recommended)        NaN   
...       ...          ...   ...                             ...        ...   
9850      Kia      Soul EV  2015                        electric        NaN   
9851      Kia      Soul EV  2015                        electric        NaN   
9852      Kia      Soul EV  2016                        electric        NaN   
9853      Kia      Soul EV  2016                        electric        NaN   
9854      Kia      Soul EV  2016                        electric        NaN   

      Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
539                0.0      DIRECT_DRIVE  front wheel drive              2.0   
540                0.0      DIRECT_DRIVE  front wheel drive              2.0   
541                0.0      DIRECT_DRIVE  front wheel drive              2.0   
2905               6.0         AUTOMATIC    all wheel drive              4.0   
2906               6.0         AUTOMATIC  front wheel drive              4.0   
...                ...               ...                ...              ...   
9850               0.0      DIRECT_DRIVE  front wheel drive              4.0   
9851               0.0      DIRECT_DRIVE  front wheel drive              4.0   
9852               0.0      DIRECT_DRIVE  front wheel drive              4.0   
9853               0.0      DIRECT_DRIVE  front wheel drive              4.0   
9854               0.0      DIRECT_DRIVE  front wheel drive              4.0   

     Market Category Vehicle Size  Vehicle Style  highway MPG  city mpg  \
539        Hatchback      Compact  2dr Hatchback          108       122   
540        Hatchback      Compact  2dr Hatchback          103       121   
541        Hatchback      Compact  2dr Hatchback          103       121   
2905          Luxury        Large          Sedan           25        17   
2906          Luxury        Large          Sedan           27        18   
...              ...          ...            ...          ...       ...   
9850             NaN      Compact          Wagon           92       120   
9851             NaN      Compact          Wagon           92       120   
9852             NaN      Compact          Wagon           92       120   
9853             NaN      Compact          Wagon           92       120   
9854             NaN      Compact          Wagon           92       120   

      Popularity   MSRP  
539          819  31800  
540          819  31800  
541          819  31800  
2905          61  55915  
2906          61  62915  
...          ...    ...  
9850        1720  35700  
9851        1720  33700  
9852        1720  33950  
9853        1720  31950  
9854        1720  35950  

[69 rows x 16 columns]

In [10]:

database_cars.loc[database_cars['Make']=='BMW','MSRP'].mean()


61546.76347305389

In [11]:

newdf=database_cars;



In [12]:
database_cars['Engine HP'].fillna(database_cars['Engine HP'].mean(),inplace=True)



In [13]:

database_cars['Engine HP'].mean()

249.38607007176023

In [14]:

database_cars.loc[database_cars['Make']=='Rolls-Royce']


Make                   Model  Year             Engine Fuel Type  \
2921   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3505   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5275   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5284   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
7443   Rolls-Royce               Park Ward  2001  premium unleaded (required)   
7444   Rolls-Royce               Park Ward  2002  premium unleaded (required)   
7553   Rolls-Royce           Phantom Coupe  2014  premium unleaded (required)   
7554   Rolls-Royce           Phantom Coupe  2015  premium unleaded (required)   
7555   Rolls-Royce           Phantom Coupe  2016  premium unleaded (required)   
7556   Rolls-Royce  Phantom Drophead Coupe  2014  premium unleaded (required)   
7557   Rolls-Royce  Phantom Drophead Coupe  2015  premium unleaded (required)   
7558   Rolls-Royce  Phantom Drophead Coupe  2016  premium unleaded (required)   
7559   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7560   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7561   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7562   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7563   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
7564   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
9431   Rolls-Royce           Silver Seraph  2001  premium unleaded (required)   
9432   Rolls-Royce           Silver Seraph  2002  premium unleaded (required)   
11448  Rolls-Royce                  Wraith  2014  premium unleaded (required)   
11449  Rolls-Royce                  Wraith  2015  premium unleaded (required)   
11450  Rolls-Royce                  Wraith  2016  premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921       325.0               8.0         AUTOMATIC  rear wheel drive   
3505       563.0              12.0         AUTOMATIC  rear wheel drive   
5275       563.0              12.0         AUTOMATIC  rear wheel drive   
5276       563.0              12.0         AUTOMATIC  rear wheel drive   
5277       563.0              12.0         AUTOMATIC  rear wheel drive   
5278       563.0              12.0         AUTOMATIC  rear wheel drive   
5279       563.0              12.0         AUTOMATIC  rear wheel drive   
5280       563.0              12.0         AUTOMATIC  rear wheel drive   
5281       563.0              12.0         AUTOMATIC  rear wheel drive   
5282       563.0              12.0         AUTOMATIC  rear wheel drive   
5283       563.0              12.0         AUTOMATIC  rear wheel drive   
5284       563.0              12.0         AUTOMATIC  rear wheel drive   
7443       322.0              12.0         AUTOMATIC  rear wheel drive   
7444       322.0              12.0         AUTOMATIC  rear wheel drive   
7553       453.0              12.0         AUTOMATIC  rear wheel drive   
7554       453.0              12.0         AUTOMATIC  rear wheel drive   
7555       453.0              12.0         AUTOMATIC  rear wheel drive   
7556       453.0              12.0         AUTOMATIC  rear wheel drive   
7557       453.

In [15]:

NW=database_cars.loc[
    database_cars['Make']=='Rolls-Royce',['Engine HP','Engine Cylinders','highway MPG']
]

DS=NW.drop_duplicates()


display(DS)


Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [16]:
import numpy as np

X= DS.to_numpy()


display(X);



array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [17]:
T=X.transpose()

# THIS IS CORRECT
XTX = T.dot(X)
display(XTX)

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [18]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv.sum()

y=[1000,1100,900,1200,1000,850,1300]

LINEAR REGRESSION

$$W=(X^T X)^{-1} * X^T Y$$


In [19]:
W= XTX_inv.dot(T).dot(y)

display(W)

array([ 0.19989598, 31.02612262, 31.65378877])

In [20]:
display(T)

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])