In [1]:

import numpy as np;

print(np.zeros(5));
np.full(10,2.5);

[0. 0. 0. 0. 0.]


In [2]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])

Randomly generated arrays


In [3]:
n[2]=[1,1,1]

In [4]:
print(n);

[[1 2 3]
 [4 5 6]
 [1 1 1]]


In [5]:
np.random.seed(2) #Seed allows the value to be fixed
print(np.random.rand(5,2));

[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]


In [6]:
%config Completer.use_jedi = False

In [7]:
#Values for the normal distribution

In [8]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])